### ISSUE TITLE
FP MoM: black box

### ISSUE THREAD

**Issue by Illegit** [EdoFro/Freeplane_Menu-o-Matic#13]
**Describe the bug**
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/ae07f505-1093-4057-8b68-1122a99610bb)
in the attachment you will see 2 black boxes, they have been created by right-clicking the menu-o-matic dialog menu and drag it in the middle between the tabbed menu and the map (see the attachment again), after you cannot delete them until you close FP and restart it.

W11
FP 1.11.7
Mom last version

**Comment by EdoFro** [comment]
Yep, I discovered this too, but couldn't correct it.

As you said, this happens when right-clicking a menu-o-matic dialog menu and drag it on the map.

BUT:

- it becomes only a problem, if you then click on the "Remove Toolbar" pop up menu that has appeared, because it closes the menu dialog that is the parent of that empty box and you lost any "connection" to it.

- If you don't click on "Remove Toolbar", then you can left click on the same dialog menu to drag'n drop it and it will refresh the position of the empty box and remove it after the dragging.


https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/54f7ece8-5754-4730-9ec6-5d6545b4d4e3

**Comment by EdoFro** [comment]
I wasn't able to do any of these:
- access the empty box after its parent dialog was removed
- avoid "remove toolbox" pop up menu from appearing when dragging the dialog

**Comment by EdoFro** [comment]
I didn't try these:
- remove the dragging box when removing the dialog
- interrupt the dragging "state" when removing the dialog

**Comment by Illegit** [comment]
Thank you EdoFro, clear.

**Comment by Illegit** [comment]
I 'll follow your indications

**Comment by EdoFro** [comment]
I made a little trick and solved this issue

**Comment by EdoFro** [comment]
@Illegit,
Can you please test the new version and tell me if this issue is solved?

#16

**Comment by EdoFro** [comment]
here is my test.
I clicked first with the right button a few times and then with the left button and then with the right button again


https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/d9d0afb2-f4ac-4981-9410-17c91ef68176

**Comment by EdoFro** [comment]
Hi @Illegit,
Did you test the last addon version: #16 ? 
any comments?

I also released a [new version](https://github.com/EdoFro/Freeplane_TabbedPanelMod/releases/tag/v0.5) from [TabbedPaneMod](https://github.com/EdoFro/Freeplane_TabbedPanelMod). It works better with MoM.

**Comment by Illegit** [comment]
Hi EdoFro, Mom (last version) is working nicely, not any problem with the black box. Now in this version, I understand that to remove a bar after I moved it out of the right panel I need to right-click, click remove bar, and click the X to close the bar. Maybe not so smooth but in any case effective. 
It is working well.

I tried even the new tabbed panel: I think it is working appropriately. I do not understand your last changes because normally I do not use those characteristics (at least consciously)
Here are the bars I use every day: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/96e87a22-dbd0-4504-8fff-15c3cd12a3f4)
Thanks.

**Comment by Illegit** [comment]
I appreciate your new icons. Well done.

**Comment by Illegit** [comment]
Hi EdoFro, I applied both of your add-ons in the last versions: MoM is working quite well. I have understood that to delete the bar once it has been moved out of the tabbed panel I have first to click remove bar and after delete click the X on the bar (not so smooth, but effective). 

About the tabbed panel, I do not understand exactly what are the new changes, it is working well. Maybe I use unconsciously the new characteristics. 
I use both every day and here is my last normal tabbed panel with MoM: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/5e990f42-a479-4633-bd81-a71d20ff54ee)
it is more readable. Thanks.
PS: I'm curious: how to add other menus to the tabbed panel (as in your image the MDI?)

**Comment by EdoFro** [comment]
> PS: I'm curious: how to add other menus to the tabbed panel (as in your image the MDI?)

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/46a4c6c7-f64f-45bc-a5ff-1e9cbfae2a74)

"Place toolbar into tab:"

and the Tab takes the icon of the MoM Package node

(MoM creates the Tab if there is no tab with that name)

---> 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/852a4490-c142-48f6-80cc-81c492bbde4a)

**Comment by EdoFro** [comment]
> I have understood that to delete the bar once it has been moved out of the tabbed panel I have first to click remove bar and after delete click the X on the bar (not so smooth, but effective).

or click the x on the bar, then it returns to the tabbed panel, and there you can right click and delete it.

It is not something I have defined, it works this way and I don't know if I can change it.

**Comment by Illegit** [comment]
> "Place toolbar into tab:"

I like it, thanks.

> or click the x on the bar, then it returns to the tabbed panel, and there you can right-click and delete it.

My feeling is that this is not an issue, but the normal way how it has to work.

**Comment by Illegit** [comment]
Understood: wow! Everything is smooth. It is increasing the FP usability during teamwork and especially during improvement sessions and analysis activities. this menu personalization is really powerful. Now I'm reviewing my menu tabs for tomorrow's activities.
