### ISSUE TITLE
FP 1.11.11_01: TabbedPanel and MoM do not start automatically

### ISSUE THREAD

**Issue by Illegit** [EdoFro/Freeplane_Menu-o-Matic#17]
**Describe the bug**
FP 1.11.11_01: TabbedPanel and MoM do not start automatically as in the previous version FP 1.11.10. I did not change any settings, I just installed the new FP version

**Screenshots**
here is my log file
[log - Copia.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/14231813/log.-.Copia.zip)
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/e2b2fcc8-f1bd-4064-bf44-907656c51ec1)

**Desktop:**
 - OS: [e.g. iOS]W11
 - AddOn version: MoM 0.1.11 and TabbedPanel 0.5
 - Freeplane Version: FP 1.11.11_01

**Additional context**
In FP 1.11.10, all the Tabbed Panel start immediately with m actual settings and MOM read the auto execution command.

**Comment by EdoFro** [comment]
EDIT: look at [my last comment](https://github.com/EdoFro/Freeplane_Menu-o-Matic/issues/17#issuecomment-1939163536) before.

Hi @Illegit,
can you reinstall the previous version and attach here its Log file too?

The current file shows many errors, and I want to see which of them appears only in the new FP version. (I have not installed it yet)

It seems to me, that it has some problem loading the libraries

**Comment by EdoFro** [comment]
For example:

this error:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/b0cf5080-0f08-4b31-9106-8fa477441d21)

refers to the use of ["config" which is "global variable" in Freeplane](https://docs.freeplane.org/api/org/freeplane/plugin/script/FreeplaneScriptBaseClass.ConfigProperties.html)
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/a9ac280c-ee09-49a9-b9cf-c2ffa7af566c)

So, I don't know if FP does load it after the execution of the ini scripts or if it doesn't load it at all.

or maybe FP loads all libraries, but it doesn't initialize them as 'global variables' like 'config', 'ui', etc.

**Comment by EdoFro** [comment]
Hi @Illegit,
I installed FP 1.11.11_01 and I had no problem at all. I compared my two Log files (before: FP 1.11.09 vs after: FP 1.11.11_01) and they are the same (aside from obvious differences like 'version number'', 'git revision' and time stamps).

Sorry, I think you have a problem with your preferences files, userDirectory or something like that.

here is how my Log file looks after starting FP (much shorter than yours, without Warnings and Errors):

```
STDOUT: Feb 12, 2024 1:45:24 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.11; freeplane_xml_version = freeplane 1.11.5
git revision = e297e89b5922d58e27863b455d921f3596d085ae dpolivaev 2024-02-06T15:14:41Z
java_version = 17.0.6; os_name = Windows 11; os_version = 10.0
STDOUT: Feb 12, 2024 1:45:25 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format dd-MM-yy
STDOUT: Feb 12, 2024 1:45:25 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format dd-MM-yy HH:mm
STDOUT: Installing shutdown hook.
STDOUT: Framework launched
STDOUT: Feb 12, 2024 1:45:28 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://4:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Feb 12, 2024 1:45:28 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\groovyConsole\lib\groovyConsole.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\groovyNode\lib\groovyNode.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\mapDriveInator\lib\MapDriveInator.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\mapSavingOptions\lib\MapSavingOptions.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\MarkdownHelper.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\jsoup-1.10.2.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\markedj-1.0.16.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\menuOMatic\lib\Menu-o-Matic.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\pseudoFreeplaneAPI\lib\pseudoFreeplaneAPI.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\stylesColorShifter\lib\StylesColorShifter.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tabbedPanelMod\lib\TabbedPanelMod.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\Tutorial-o-Matic.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\markedj-1.0.16.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\jsoup-1.10.2.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\unicodeProgressBar\lib\UnicodeProgressBar.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\jcommon-1.0.24.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\jfreechart-1.5.3.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\json-simple-1.1.1.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\MDTool-1.2.4.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\plantuml.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\scriptlib.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x]
STDOUT: Feb 12, 2024 1:45:28 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://9:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Feb 12, 2024 1:45:29 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Feb 12, 2024 1:45:29 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Feb 12, 2024 1:45:30 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Feb 12, 2024 1:45:37 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\BookmarksMonitorIcons.groovy
STDOUT: Feb 12, 2024 1:45:37 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\TabbedPanelMod_init.groovy
STDOUT: Feb 12, 2024 1:45:37 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: [addons.tabbedPanelMod.TabbedPanelMod_on_single_node]
STDOUT: Feb 12, 2024 1:45:37 PM org.freeplane.core.util.LogUtils info
INFO: executing Tabbed panel mod(addons.tabbedPanelMod.TabbedPanelMod_on_single_node)
STDOUT: modifyTab: tabName Format
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: tabName Attributes
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: tabName Calendar
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: tabName Presentations
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: Feb 12, 2024 1:45:38 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\Tabz_Menu-o-Matic_init.groovy
STDOUT: Feb 12, 2024 1:45:39 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: [addons.menuOMatic.1launchMenuOMaticDialog_on_single_node]
STDOUT: Feb 12, 2024 1:45:39 PM org.freeplane.core.util.LogUtils info
INFO: executing launch Menu-o-Matic dialog(addons.menuOMatic.1launchMenuOMaticDialog_on_single_node)
STDOUT: MoM: Looking for tab 'MoM' --> tab's index: -1
STDOUT: MoM: tab 'MoM' was created
STDOUT: MoM: edofro.tabbedpanelmod.TPM.modifyTab(4)
STDOUT: modifyTab: tabName MoM
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab null
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: TPM: Tab 4 modified
STDOUT: MoM init: - opening AutoLaunchCustomMenus from following mind maps:
STDOUT: MoM AUTO: |- mindMap: 'CustomMenus'
STDOUT: MoM AUTO: |  - [MDI, MDI mantención, MDI tools]
STDOUT: MoM: Looking for tab 'MoM' --> tab's index: 4
STDOUT: MoM: Looking for tab 'MoM' --> tab's index: 4
STDOUT: MoM: Looking for tab 'MDI tools' --> tab's index: -1
STDOUT: MoM: tab 'MDI tools' was created
STDOUT: MoM: edofro.tabbedpanelmod.TPM.modifyTab(5, 'emoji-1F4BF')
STDOUT: modifyTab: tabName MDI tools
STDOUT: modifyTab: iconForTab emoji-1F4BF
STDOUT: modifyTab: FPTabPane.tabIconNames [:]
STDOUT: modifyTab: iconForTab emoji-1F4BF
STDOUT: modifyTab: FPTabPane.tabIconNames [MDI tools:emoji-1F4BF]
STDOUT: TPM: Tab 5 modified
STDOUT: MoM AUTO: |- mindMap: 'Mochila'
STDOUT: MoM AUTO: |  - []
STDOUT: Feb 12, 2024 1:45:40 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []


```

**Comment by Illegit** [comment]
[log - FP1.11.11_01.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/14271737/log.-.FP1.11.11_01.zip)
[log - FP1.11.10 stable.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/14271738/log.-.FP1.11.10.stable.zip)
Here are the 2 logs with the installation of FP 1.11.10 stable and with the installation of FP 1.11.11_01, before doing these installations I canceled 1 svg icon that wasn't readable, and after that, both of the installations were working correctly with TabbedPanel and with MOM. Still there plenty of errors and some help to identify what to clean will be useful, but it was that icon that was blocking FP 1.11.11_01 and not the previous ones... strange.

**Comment by Illegit** [comment]
note that with FP 1.11.10 stable I deleted the codexplorer.json as suggested by Dimitry, Instead I left it with FP 1.11.11_01.

**Comment by EdoFro** [comment]
Hi @Illegit,
I took a look at your log files.

I think I would, in your case, uninstall all the addons, move the script files and libraries to other folders temporarily and restart FP again. Then I would recheck the Log files and see what errors remain.

I would probably also move the compiled script files to other temporary folders (or delete them to be sure they are recompiled)

Beeing specific: I would move the contents of the following folders to temporary folders:
- addons
- compiledscripts
- compiledscripts2
- lib
- scripts

just to be sure there is no conflict between the scripts and Freeplane.

good luck,

edo

**Comment by EdoFro** [comment]
maybe a first step would be:
- lib
- compiledscripts
- compiledscripts2

I think you have pretty old stuff in the lib folder.

**Comment by Illegit** [comment]
sure, thanks for the help I'll do and feedback.

**Comment by Illegit** [comment]
Done, now things are working here the log: 
[log - Copia (3).zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/14319850/log.-.Copia.3.zip)
there is this error that I do not know which is the source...
Thanks

**Comment by EdoFro** [comment]
HI @Illegit,

I think this error:
```
STDOUT: Feb 17, 2024 7:25:49 PM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
```

is because you added some svg Icons that have their own CSS StyleSheet and the version of the library **kitfox** is not able to parse them.

So, in my opinion, it's not a fault of Freeplane nor your icons, it is just a message from the library saying that it can't handle this yet, it has not been implemented yet.

you can look at [this in svgSalamander](https://github.com/blackears/svgSalamander/blob/c22c3add54241c34b2dda1eb34ed3d40e4a0b671/svg-core/src/main/java/com/kitfox/svg/xml/StyleSheet.java#L20-L26) repository:

```java
    public static StyleSheet parseSheet(String src)
    {
        //Implement CS parser later
        Logger.getLogger(SVGConst.SVG_LOGGER).log(Level.WARNING,
            "CSS parser not implemented yet");
        return new StyleSheet();
    }
```

**Comment by EdoFro** [comment]
@Illegit,
I 've notice that You have had some problems with custom icons.

When I want to create my own icons for Freeplane I do this:
1. I create the icon in Inkscape
2. I export the icon as Optimized SVG (*.svg)

**Comment by EdoFro** [comment]
@Illegit,
About this error:
```java
STDERR: Feb 17, 2024 7:26:29 PM org.freeplane.core.util.LogUtils severe
SEVERE: Can not process attribute CHILD_NODES_LAYOUT = 'AUTO_BYFIRSTCHILD'
java.lang.IllegalArgumentException: No enum constant org.freeplane.api.ChildNodesLayout.AUTO_BYFIRSTCHILD
	at java.base/java.lang.Enum.valueOf(Unknown Source)
```

it relates with [this issue (reported by you)](https://github.com/freeplane/freeplane/issues/1166)

and you have to do the [solution recommended by Dimitry](https://github.com/freeplane/freeplane/issues/1166#issuecomment-1557932309).

You can use Notepad++ for this.
