### ISSUE TITLE
Automatically open some MoM menus when you start FP.

### ISSUE THREAD

**Issue by EdoFro** [EdoFro/Freeplane_Menu-o-Matic#2]
Hi EdoFro, is it possible to apply the same approach as for Tool Panel addon menu, to some of the menu-o-matic solutions?  In order to have the possibility to have some of them already open when you startP FP.
Thanks.

_Originally posted by @Illegit in https://github.com/freeplane/freeplane/discussions/368#discussioncomment-6620094_

**Comment by EdoFro** [comment]
Hi @Illegit,
How do You imagine this feature?

1. It should launch automatically all the MoM nodes from a map or just some of them?
    - I think only some of them
    - for example, the ones that have a special attribute
      - "MoM_autoLaunch": true

2. It has to launch the MoM nodes from which mindMap?
    Alternatives:
    - From the active mindMap when FP starts
    - From all loaded mindMaps when FP starts
    - Only from a map named as "MoM_myToolbox.mm" and only if it is loaded.
    - From a map that the user can define in FP preferences (setting the path to its file), and FP opens it headless (hidden) 
    - a combination of them

3. Should this also work everytime Freeplane opens a mindMap?
    - I think if its MoM nodes have the attribute, then they should be launch.
    - we can use Macmarrun's script for this

4. which of this options should be present in FP Preferences dialog?

BR
edo

**Comment by Illegit** [comment]
I think it could be even more than expected.
Nice to have them.
Thanks to think about it

**Comment by EdoFro** [comment]
Hi @Illegit,
I released a [new version of the addon that has this functionality](https://github.com/EdoFro/Freeplane_Menu-o-Matic/releases/tag/v0.1.5)

This is a first version, and I think it should be good enough for now.

1. only marked customMenu nodes are automatically launched
2. all marked menus form all opened maps are launched when starting Freeplane
3. when opening a mindMap that has AutoLaunch menus, they are automatically launched

to mark a customMenu node as "AutoLaunch", you have to add the 'launch' icon to it (it's a rocket:🚀)

like this:

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/c97be05c-7454-4606-ae5b-6ee503f49d75)

**Comment by Illegit** [comment]
Hi EdoFro, it is working as expected: Nice!
Thanks

**Comment by EdoFro** [comment]
ehhhh, It throws an error when creating a new map. sorry.

I released a corrected version.

**Comment by EdoFro** [comment]
ok. I think it is done.

**Comment by Illegit** [comment]
Got it. Confirmed. Thanks.

**Comment by EdoFro** [comment]
@Illegit,
please take a look at [this topic](https://github.com/EdoFro/Freeplane_Menu-o-Matic/issues/5).

thanks,
edo
