### ISSUE TITLE
project Menu-o-Matic v0.2.0

### ISSUE THREAD

**Issue by EdoFro** [EdoFro/Freeplane_Menu-o-Matic#5]
Dear @Illegit,
I'm working in a new version of **Menu-o-Matic** and I want to have your opinion.
I don't know how many users this add-on has, but You have been kind enough to share your comments with me and I appreciate that. Thank you.

This version points on how I always imagined **Menu-o-Matic** should work: custom menus in Freeplane's ToolPanel. I still have to polish some details, but I'm interested in You using it and giving me your feedback as soon as possible.

Consider that this version represents the direction in which I intend to guide the future development of this add-on. There are some features of the previous version that may disappear, but I have the impression that they will not be missed.

I won't explain more so that you can find out on your own and not bias your judgment.

Thank you very much, 

I've attached a zip file with test versions of **Menu-o-Matic** and **TabbedPanelMod**.

The test version of **Menu-o-Matic** doesn't require **TabbedPanelMod** to be active, but if you want to use both, then you must also upgrade **TabbedPanelMod** to its test version.

[Menu-o-Maticv0.2.beta.addon.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/12328321/Menu-o-Maticv0.2.beta.addon.zip)

BR

edo

**Comment by Illegit** [comment]
Hi EdoFro, downloaded them and in use. Only point I'm on holidays at now with limited use of my pc. It could be that I need some days to feedback you.

**Comment by Illegit** [comment]
Hi EdoFro, as a first impact I like it. Now I must use it for a short time, follwing some immediate feedbacks.
1) In the load of the addon I got a problem
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/324828e9-8495-4889-9acb-e2c645e359d8)
This happens for both the addon files, it doesn't upgrade from previous version already installed. I have to uninstall theme and after install the new addons
2) see this cut of the icons on the left, if I change the size of the bar to see the icons in full, it doesnt memorize the new size ego back to the cut icon size: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/ea5d5c0c-d221-4314-93c7-72f6586dea4c)
3) make the arrows more visible (may be a little bigger): 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/d9d7bb7a-1be2-464d-a714-fec2c5ef4357)

**Comment by Illegit** [comment]
4) as you can see in my menu I created some icons LINK, MDH, ICONS, ... describing the chapters of the menu, is it possible to create just the possobility to name some chapters inside the menu?

**Comment by Illegit** [comment]
5) is it possible to change the color background of the menu?

**Comment by Illegit** [comment]
with reference to my comment 4), I see that maybe could be better just to change the "..." with the name of the menu , in my case "Options" and with your solution there is not need any longer to create chapters! Nice. so please delete my 4) comment.

**Comment by EdoFro** [comment]
Hi Illegit,
about:
1. No idea. Maybe it is because I changed the addon's file name manually (adding the "beta" part)
2. Ok. I defined the "collapsed" width in 40 (¿pixels?). I think I have to change this to look at the tabs width and define the collapsed width to something like "tabs width + 5". Or maybe I have to define it in points and not in pixels. I will investigate a little more.
3. The "arrows" are two icons from the emoji addon. I haven't created special icons for this. I will do that.
   This is how it looks in my computer:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/6340b3c7-5f6b-4945-ad3a-402cec43615a)

4. I'm thinking in adding the possibility to add horizontal Separators in each Menu (toolbar). I don't know yet how it will be. I don't know how to add Titles to each toolbar yet.
5. ¿from each one or from the whole panel? I like the idea from each one.

 the "..." is a handle for the mouse to "drag'n drop" the toolbar. 

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/ad57498e-4ea8-42fc-ad44-f1ad2eb19003)

**Comment by Illegit** [comment]
5. yes I was thinking of each one.

**Comment by Illegit** [comment]
Hi EdoFro, I installed the new add-ons on another pc (always w11) and topics 1. and 2. were not present, so I understood they happened only in 1 pc... probably they are not so important to tackle, about the 2. on this 2nd pc the size was ok, maybe it is necessary to propose a customizable size if it is possible, but I think the topic is not so important. (1st pc is a surface, 2nd pc is a dell)

**Comment by EdoFro** [comment]
> 2\. Ok. I defined the "collapsed" width in 40 (¿pixels?). I think I have to change this to look at the tabs width and define the collapsed width to something like "tabs width + 5". Or maybe I have to define it in points and not in pixels. I will investigate a little more.

done

**Comment by EdoFro** [comment]
> 5\. yes I was thinking of each one.

done

**Comment by EdoFro** [comment]
now tabbed Panels widths are stored in drive (widths are loaded when restarting Freeplane)

**Comment by Illegit** [comment]
2. working in surface: OK
About the color, I haven't understood: here my screen cropping 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/f229f44c-d519-4627-b565-77fff69a456b)
as you can see on the left there is the package and on the right the menu (look the first 3 nodes) there isn't any change of color in the menus.

**Comment by EdoFro** [comment]
in my computer
this node's format:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/d3659a23-e44f-4988-952a-78bda2eb0ed1)

creates this toolbar:

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/dc7a2918-31ce-453e-aaf3-47c3e6e79288)

**Comment by Illegit** [comment]
About the color, if I apply a style to the package node, the color doesn't change it remains as the menu background (see my previous screen crop), instead if I change the color background and/or text with the format menu it happens as you describe: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/8b194bf8-d427-4825-a407-e75e9f63ebf2)

Ok now that I  have understood, the solution is working. Thanks. At now for me, it is not urgent to approach furtherly this topic

**Comment by EdoFro** [comment]
Thanks for your feedback. I 'm going to test it for a few days to see if there are more bugs.

I'm already happy with the result, so I don't expect to make major modifications to the addon (at least for this version).

BR

edo

**Comment by Illegit** [comment]
Here my current crop: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/6ccc8c9a-c755-444d-b3f1-3cf0a973fffe)
It is quite nice. Well done!

**Comment by Illegit** [comment]
Hi EdoFro, 2 more topics to be evaluated. in MoM
6. navigate command "list opened menu dialog" doesn't show any menu: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/3fb5cec0-47c8-425e-ab41-7cb6cd8c268e)

7. navigate command "show most recently used menu" get this error: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/d659b119-c0ac-422f-a920-4537199da092)

**Comment by EdoFro** [comment]
Ok. I have to remove those commands. Thanks

I did a little change for the next version: 

I added titledBorders to toolbars.

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/ac48369b-fbd0-43d6-9dda-2cc96e1598ab)

I think it looks better, not?

**Comment by EdoFro** [comment]
I updated the addon file. Now it should work.

**Comment by Illegit** [comment]
Hi EdoFro, installation is working fine. Nice solution. I like it.
Let me propose to you these 3 topics:
1) There is a bug because it doesn't launch the menus with the rocket, as before. Did you change the icons to launch them?
2) Is it possible to leave the user the choice of applying the previous format (more compact) or this one (nice)?
3) Is it possible in this last format (nice) to leave the user to choose the title character size?
Thanks

**Comment by Illegit** [comment]
1. About 1 I saw your new attribute! Answered. There are no longer icons. Well done.
2. So please have a look at the other 2 topics.

**Comment by EdoFro** [comment]
Hi Illegit,

> Is it possible to leave the user the choice of applying the previous format (more compact) or this one (nice)?

In FP preferences (for all menus) or in each Menu node?

> Is it possible in this last format (nice) to leave the user to choose the title character size?
Thanks

In FP preferences (for all menus) or in each Menu node?

----

I don't want to add so many parameters for each menu. It should remain simple.

Maybe give the possibility as user preferences.

**Comment by Illegit** [comment]
yes, I was thinking as user preferences. in the preferences menu.

**Comment by EdoFro** [comment]
Here is a new version to test.
[Menu-o-Matic-v0.1.8.addon.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/12478882/Menu-o-Matic-v0.1.8.addon.zip)

now it supports "separators":
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/e5194a89-0656-4653-b895-10965b1b0563)


To see how does that work do:

1. `Edo Tools->Menu-o-Matic->Design->Insert Menu-o-Matic package node`
2. select the inserted node
3. `Edo Tools->Menu-o-Matic->Design->unpack menu`
4. look how the separators were added
   - nodes between the button nodes with '---' as text

![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/ac7d4936-6ef0-4420-89d5-1ebeb8941df4)


# History

## v0.1.8

* init script opens Menu o Matic toolbar
* Added preference to show/hide Menu-o-Matic toolbar buttons labels
* Added menu separators
* Toolbar title can be modified in dialog

**Comment by Illegit** [comment]
Hi EdoFro: v0.1.8 is very nice.

**Comment by EdoFro** [comment]
@Illegit,
new version released.

## v0.1.9

1. Corrected button background color (bug in some L&F)
    * In original Look&Feels the buttons background weren't transparent
2. Added preference to (in)activate TitledBorders
3. Added popup menu to remove toolbars
    * Right clicking on toolbars
4. Added powerButtons functionality
    * Unifies multiple MenuActions nodes as a single "powerButton" that executes all actions at once

## 2. Added preference to (in)activate TitledBorders
> Is it possible to leave the user the choice of applying the previous format (more compact) or this one (nice)?

this can be defined in preferences:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/ce27a6cd-4dbf-4e6f-9076-77472aaf4299)

## 3. Added popup menu to remove toolbars
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/01bde786-b06c-4c7a-9532-cb355f9aca9b)

## 4. Added powerButtons functionality

This:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/e358085c-a842-4bcb-87b7-422f6a38a1b2)

launches this toolbar:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/e27dc8f3-d01e-46f3-a567-a022eb25e667)

Then, when clicking, for example, on the "incorrect" button, a node goes from:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/7e76a860-7482-415f-961b-de334a888567)

to:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/623a7b05-692c-47ee-bbfa-cafbb9e07b92)

in just one click.

Look at the  example mind map attached with this release.

Tell me what you think.

Regards,

edo

**Comment by Illegit** [comment]
Wow!
Now there are so many possibilities!
Preferences are working well.

Just  a small note: In the second power button I got the following error
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/c73c0611-b53e-4d42-bec1-9681bba89319)
This error has been generated by this power button: 
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/62674157/80331401-3bf9-48d3-833e-d401f8d6c407)

but I tried other icon combinations and powerbutton tool worked fine. I enjoy using it.

PS: If you want to think of some more topics: I see the bars for icons & labels are horizontal, If you use just icons, horizontal bars are not working well, in this case, more often you need to have vertical bars then horizontal ones.

**Comment by EdoFro** [comment]
I think the error is because I have the emoji icons added to the menus and icon Bar and maybe you don't:

in preferences:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/6f942301-8c0a-41e5-8b58-6c13346290f8)

this is how that branch looks in my computer:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/042a33b4-b72b-456e-b175-698d1d270b3e)

**Comment by EdoFro** [comment]
> PS: If you want to think of some more topics: I see the bars for icons & labels are horizontal, If you use just icons, horizontal bars are not working well, in this case, more often you need to have vertical bars then horizontal ones.

Ha,ha,ha! I like them horizontal in my only icons toolbars!!

I try to use toolbars with icons in a different tab than the toolbars with label.
and I narrow as much as possible that "only icons" tab. In that cas horizontal separators work perfect.

I will think about it. maybe there is a solution for both use cases

**Comment by Illegit** [comment]
bars= separators, An alternative I was thinking of activating, just in case, is to utilize the attribute icons in SVG (this svg is smaller in width than the others), change its color, and apply it as a separator eventually... plan B.
But I can survive without it... 
...this addon is already very useful, I use it continuously, even your last features: powerbutton & remove button.

**Comment by Illegit** [comment]
to create the vertical separator you can use the symbol "|".

**Comment by EdoFro** [comment]
I have a new version. I can´t upload it as release right now, but it will be like this:

[Menu-o-Matic-v0.1.10.addon.zip](https://github.com/EdoFro/Freeplane_Menu-o-Matic/files/12501665/Menu-o-Matic-v0.1.10.addon.zip)


## v0.1.10

* Unpacking powerButtons now gets the labels for icon buttons too
* Added popup menu to remove Tabs
  * Right clicking on tab, (not on toolbars)
  * ![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/8f276152-d08a-47eb-8f60-906cc81716c3)

* Added vertical separators
  * node text =  `|`

This branch:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/cd3585cc-bb26-4f33-905e-3710f002744a)

produces this toolbar:
![image](https://github.com/EdoFro/Freeplane_Menu-o-Matic/assets/35700575/86535ba8-b4a6-4f94-b7a8-1f65626deb18)

**Comment by EdoFro** [comment]
I don’t know why, when adding separators, the toolbars go so wide.
That’s my next “quest”

**Comment by Illegit** [comment]
Ok, quite customizable by the user with this 2 kinds of separators.
Yes, I understand that the width is important to be managed otherwise isn't possible to place other bars in parallel.

**Comment by EdoFro** [comment]
Hi @Illegit 

> 3\. Is it possible in this last format (nice) to leave the user to choose the title character size?

look here #12 

I think it is ready. I will use it a few more days to see if there are other relevant bugs and publish it as v0.2.0

I have to look at the documentation also.

Can you please test it and comment in #12?

Thanks
